[build]
nixpacks = true

[build.args]
NIXPACKS_ROOT = "PuntoSabor-Backend"

[deploy]
start = "dotnet PuntoSabor-Backend.dll"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
